version: 2.1
orbs:
  go: circleci/go@1.9.0
jobs:
  unit_tests:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          failfast: true
          parallel: '4'
          race: true
workflows:
  test:
    jobs:
      - unit_tests
