version: 2.1
orbs:
  go: circleci/go@1.9.0
jobs:
  unit_tests:
    executor:
      name: go/default
      tag: '1.22'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: Download bingo modules
          command: |
            make
      - run:
          name: Generate mocks
          command: |
            go generate ./...
      - go/save-cache
      - go/test:
          covermode: 'atomic'
          failfast: true
          parallel: '4'
          race: true
  lint:
    executor:
      name: go/default
      tag: '1.21'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: Download bingo modules
          command: |
            make
      - run:
          name: Generate mocks
          command: |
            go generate ./...
      - go/save-cache
      - run:
          name: Run golangci-lint
          command: |
            golangci-lint run
workflows:
  test:
    jobs:
      - unit_tests
      - lint
